### ISSUE TITLE
toString for Request

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/libcloogle#1]
We could use a `toString` for `Request` which represents the request as a string that could be fed to the HTTP API on cloogle.org. This should have the type `Request -> Maybe String`, as some requests are invalid (like when both `className` and `typeName` are `Just`).

**Comment by dopefishh** [comment]
Yes, this can be used for telegram, IRC and mail

On 12 July 2017 18:08:15 CEST, Camil Staps <notifications@github.com> wrote:
>We could use a `toString` for `Request` which represents the request as
>a string that could be fed to the HTTP API on cloogle.org. This should
>have the type `Request -> Maybe String`, as some requests are invalid
>(like when both `className` and `typeName` are `Just`).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/clean-cloogle/libcloogle/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
