### ISSUE TITLE
Add a basic request function

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/libcloogle#2]
If we add a basic `request :: Request *World -> *(MaybeErrorString Response, *World)` which runs a query on cloogle.org, implementing a new frontend becomes trivial.

Another function could use a `String` instead of a `Request` to handle one-string queries like on cloogle.org.

(For this, we can use the doRequest function first created in https://github.com/camilstaps/clpm/blob/master/CLPM/Util.dcl#L15 and now used in multiple applications. It should be added to Internet.HTTP in Platform.)

**Comment by dopefishh** [comment]
And the code from clean-irc. It even follows redirects

On 12 July 2017 18:13:07 CEST, Camil Staps <notifications@github.com> wrote:
>If we add a basic `request :: Request *World -> *(MaybeErrorString
>Response, *World)` which runs a query on cloogle.org, implementing a
>new frontend becomes trivial.
>
>(For this, we can use the doRequest function first created in
>https://github.com/camilstaps/clpm/blob/master/CLPM/Util.dcl#L15 and
>now used in multiple applications. It should be added to Internet.HTTP
>in Platform.)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/clean-cloogle/libcloogle/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dopefishh** [comment]
It's basically [this](https://github.com/clean-cloogle/clean-irc/blob/master/cloogle.icl#L115) without the string processing
